{
 "title": "Cassandra",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "job", "label": "Application", "query": "label_values(jvm_info,job)" }
  ]
 },
 "panels": [
  {
   "title": "Cassandra requests 1min rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(cassandra_cql_requests{job=\"$job\",rate=\"1min\"}) "
    }
   ]
  },
  {
   "title": "Cassandra traffic 1min avg",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(cassandra_bytes_sent{job=\"$job\", rate=\"1min\"}) ",
     "legendFormat": "sent"
    },
    {
     "expr": "sum(cassandra_bytes_received{job=\"$job\", rate=\"1min\"}) ",
     "legendFormat": "received"
    }
   ]
  },
  {
   "title": "Client timeouts",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(cassandra_cql_client_timeouts_total{job=\"$job\"}[1m]))"
    }
   ]
  }
 ]
}