{
 "title": "Akka Dispatchers",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "job", "label": "Application", "query": "label_values(jvm_info,job)" }
  ]
 },
 "panels": [
  {
   "title": "Runnables rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(akka_sensors_dispatchers_run_time_millis_count{job=\"$job\"}[1m])) by (dispatcher)",
     "legendFormat": "{{ dispatcher }}"
    }
   ]
  },
  {
   "title": "Run time p99",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(akka_sensors_dispatchers_run_time_millis_bucket{job=\"$job\"}[1m])) by (le, dispatcher))",
     "legendFormat": "{{ dispatcher }}"
    }
   ]
  },
  {
   "title": "Queue time p99",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(akka_sensors_dispatchers_queue_time_millis_bucket{job=\"$job\"}[1m])) by (le, dispatcher))",
     "legendFormat": "{{ dispatcher }}"
    }
   ]
  },
  {
   "title": "Threads active/total",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(akka_sensors_dispatchers_active_threads_bucket{job=\"$job\"}[1m])) by (le, dispatcher))",
     "legendFormat": "{{ dispatcher }} active"
    },
    {
     "expr": "sum(akka_sensors_dispatchers_threads_total{job=\"$job\"}) by (dispatcher)",
     "legendFormat": "{{ dispatcher }} total"
    },
    {}
   ]
  },
  {
   "title": "Threads per state/dispatcher",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(akka_sensors_dispatchers_thread_states{job=\"$job\"}) by (dispatcher, state)",
     "legendFormat": "{{ dispatcher }} {{ state }}"
    }
   ]
  },
  {
   "title": "Executor stats",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(akka_sensors_dispatchers_executor_value{job=\"$job\",value=\"steals\"}[1m])) by (dispatcher)",
     "legendFormat": "{{ dispatcher }} steals"
    },
    {
     "expr": "sum(irate(akka_sensors_dispatchers_executor_value{job=\"$job\",value=\"completedTasks\"}[1m])) by (dispatcher)",
     "legendFormat": "{{ dispatcher }} completed tasks"
    }
   ]
  }
 ]
}