{
 "title": "Akka Actors",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "job", "label": "Application", "query": "label_values(jvm_info,job)" }
  ]
 },
 "panels": [
  {
   "title": "Receive rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(akka_sensors_actor_receive_time_millis_count{job=\"$job\"}[1m])) by (actor)",
     "legendFormat": "{{ actor }}"
    },
    {}
   ]
  },
  {
   "title": "Receive time p99",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(akka_sensors_actor_receive_time_millis_bucket{job=\"$job\"}[1m])) by (le, actor))",
     "legendFormat": "{{ actor }}"
    }
   ]
  },
  {
   "title": "Running actors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(akka_sensors_actor_active_actors_total{job=\"$job\"}) by (actor)",
     "legendFormat": "{{actor}}"
    }
   ]
  },
  {
   "title": "Exceptions rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(akka_sensors_actor_exceptions_total{job=\"$job\"}[1m])) by (actor)",
     "legendFormat": "{{ actor }}"
    }
   ]
  },
  {
   "title": "Recovery events rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(akka_sensors_actor_recovery_events_total{job=\"$job\"}[1m])) by (actor)",
     "legendFormat": "{{ actor }}"
    }
   ]
  },
  {
   "title": "Recovery time p99",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(akka_sensors_actor_recovery_time_millis_bucket[1m])) by (le, actor))",
     "legendFormat": "{{ actor }}"
    },
    {}
   ]
  },
  {
   "title": "Activity time p99",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(akka_sensors_actor_activity_time_seconds_bucket[1m])) by (le, actor))",
     "legendFormat": "{{ actor }}"
    }
   ]
  },
  {
   "title": "Unhahdled messages rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 7 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(akka_sensors_actor_unhandled_messages_total{job=\"$job\"}[1m])) by (actor)",
     "legendFormat": "{{ actor }}"
    }
   ]
  },
  {
   "title": "Persist rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(akka_sensors_actor_persist_time_millis_count{job=\"$job\"}[1m])) by (actor)",
     "legendFormat": "{{ actor }}"
    },
    {}
   ]
  },
  {
   "title": "Persist time p99",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(akka_sensors_actor_persist_time_millis_bucket[1m])) by (le, actor))",
     "legendFormat": "{{ actor }}"
    },
    {}
   ]
  },
  {
   "title": "Persistence failures and rejects",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(akka_sensors_actor_persist_failures_total{job=\"$job\"}[1m])) by (actor)",
     "legendFormat": "{{ actor }} failures"
    },
    {
     "expr": "sum(irate(akka_sensors_actor_persist_rejects_total{job=\"$job\"}[1m])) by (actor)",
     "legendFormat": "{{ actor }} rejects"
    }
   ]
  }
 ]
}