{
 "title": "JVM metrics",
 "description": "JVM memory use, garbage collector, cpu and thread stats",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "job", "label": "Application", "query": "label_values(up,job)" },
   {
    "name": "pool",
    "label": "Pool",
    "query": "label_values(jvm_memory_pool_bytes_max,pool)"
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": " absent(jvminfo{job=\"$job\"})==1"
    }
   ]
  },
  {
   "title": "Instances",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(jvm_info{job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 1 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - max(process_start_time_seconds{job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Start time",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 7, "y": 1 },
   "format": "dateTimeAsIso",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(process_start_time_seconds{job=\"$job\"})*1000"
    }
   ]
  },
  {
   "title": "JVM Version",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "label_join(jvm_info{job=\"$job\"}, \"jdk\", \", \", \"vendor\", \"runtime\", \"version\")"
    }
   ]
  },
  {
   "title": "CPU time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(increase(process_cpu_seconds_total{job=\"$job\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Resources",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(process_open_fds{job=\"$job\"})",
     "legendFormat": "Open files"
    },
    {
     "expr": "sum(jvm_classes_loaded{job=\"$job\"})",
     "legendFormat": "Classes loaded"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_threads_current{job=\"$job\"})",
     "legendFormat": "total "
    },
    {
     "expr": "sum(jvm_threads_daemon{job=\"$job\"})",
     "legendFormat": "daemon"
    },
    {
     "expr": "sum(jvm_threads_deadlocked{job=\"$job\"})",
     "legendFormat": "deadlocked"
    },
    {
     "expr": "sum(jvm_threads_state{job=\"$job\"})  by (state)",
     "legendFormat": "{{ state }}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 4 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_bytes_used{job=\"$job\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_bytes_max{job=\"$job\"})",
     "legendFormat": "max"
    },
    {
     "expr": "sum(jvm_memory_bytes_committed{job=\"$job\"})",
     "legendFormat": "committed"
    }
   ]
  },
  { "title": "Garbage collection", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "GC time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(increase(jvm_gc_collection_seconds_sum{job=\"$job\"}[$__interval])) by (gc)",
     "legendFormat": "GC {{gc}}"
    }
   ]
  },
  {
   "title": "GC count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(jvm_gc_collection_seconds_count{job=\"$job\"}[$__interval])) by (gc)",
     "legendFormat": "{{gc}}"
    }
   ]
  },
  { "title": "Memory pools", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "$pool",
   "type": "graph",
   "gridPos": { "h": 11, "w": 4.8, "x": 0, "y": 23 },
   "repeat": "pool",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_pool_bytes_used{job=\"$job\",pool=\"$pool\"}) ",
     "legendFormat": " used"
    },
    {
     "expr": "sum(jvm_memory_pool_bytes_used/jvm_memory_pool_bytes_max{job=\"$job\",pool=\"$pool\"}) ",
     "legendFormat": "used %%"
    },
    {
     "expr": "sum(jvm_memory_pool_bytes_max{job=\"$job\",pool=\"$pool\"})",
     "legendFormat": " max"
    },
    {
     "expr": "sum(jvm_memory_pool_bytes_committed{job=\"$job\",pool=\"$pool\"}) ",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_pool_bytes_used/jvm_memory_pool_bytes_max{job=\"$job\",pool=\"$pool\"}) ",
     "legendFormat": "committed %%"
    }
   ]
  },
  {
   "title": "$pool",
   "type": "graph",
   "gridPos": { "h": 11, "w": 4.8, "x": 4.8, "y": 23 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_pool_bytes_used{job=\"$job\",pool=\"$pool\"}) ",
     "legendFormat": " used"
    },
    {
     "expr": "sum(jvm_memory_pool_bytes_used/jvm_memory_pool_bytes_max{job=\"$job\",pool=\"$pool\"}) ",
     "legendFormat": "used %%"
    },
    {
     "expr": "sum(jvm_memory_pool_bytes_max{job=\"$job\",pool=\"$pool\"})",
     "legendFormat": " max"
    },
    {
     "expr": "sum(jvm_memory_pool_bytes_committed{job=\"$job\",pool=\"$pool\"}) ",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_pool_bytes_used/jvm_memory_pool_bytes_max{job=\"$job\",pool=\"$pool\"}) ",
     "legendFormat": "committed %%"
    }
   ]
  },
  {
   "title": "$pool",
   "type": "graph",
   "gridPos": { "h": 11, "w": 4.8, "x": 9.6, "y": 23 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_pool_bytes_used{job=\"$job\",pool=\"$pool\"}) ",
     "legendFormat": " used"
    },
    {
     "expr": "sum(jvm_memory_pool_bytes_used/jvm_memory_pool_bytes_max{job=\"$job\",pool=\"$pool\"}) ",
     "legendFormat": "used %%"
    },
    {
     "expr": "sum(jvm_memory_pool_bytes_max{job=\"$job\",pool=\"$pool\"})",
     "legendFormat": " max"
    },
    {
     "expr": "sum(jvm_memory_pool_bytes_committed{job=\"$job\",pool=\"$pool\"}) ",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_pool_bytes_used/jvm_memory_pool_bytes_max{job=\"$job\",pool=\"$pool\"}) ",
     "legendFormat": "committed %%"
    }
   ]
  },
  {
   "title": "$pool",
   "type": "graph",
   "gridPos": { "h": 11, "w": 4.8, "x": 14.399999999999999, "y": 23 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_pool_bytes_used{job=\"$job\",pool=\"$pool\"}) ",
     "legendFormat": " used"
    },
    {
     "expr": "sum(jvm_memory_pool_bytes_used/jvm_memory_pool_bytes_max{job=\"$job\",pool=\"$pool\"}) ",
     "legendFormat": "used %%"
    },
    {
     "expr": "sum(jvm_memory_pool_bytes_max{job=\"$job\",pool=\"$pool\"})",
     "legendFormat": " max"
    },
    {
     "expr": "sum(jvm_memory_pool_bytes_committed{job=\"$job\",pool=\"$pool\"}) ",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_pool_bytes_used/jvm_memory_pool_bytes_max{job=\"$job\",pool=\"$pool\"}) ",
     "legendFormat": "committed %%"
    }
   ]
  },
  {
   "title": "$pool",
   "type": "graph",
   "gridPos": { "h": 11, "w": 4.8, "x": 19.2, "y": 23 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_pool_bytes_used{job=\"$job\",pool=\"$pool\"}) ",
     "legendFormat": " used"
    },
    {
     "expr": "sum(jvm_memory_pool_bytes_used/jvm_memory_pool_bytes_max{job=\"$job\",pool=\"$pool\"}) ",
     "legendFormat": "used %%"
    },
    {
     "expr": "sum(jvm_memory_pool_bytes_max{job=\"$job\",pool=\"$pool\"})",
     "legendFormat": " max"
    },
    {
     "expr": "sum(jvm_memory_pool_bytes_committed{job=\"$job\",pool=\"$pool\"}) ",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_pool_bytes_used/jvm_memory_pool_bytes_max{job=\"$job\",pool=\"$pool\"}) ",
     "legendFormat": "committed %%"
    }
   ]
  },
  {
   "title": "$pool",
   "type": "graph",
   "gridPos": { "h": 11, "w": 4.8, "x": 0, "y": 34 },
   "repeat": "pool",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_pool_bytes_used{job=\"$job\",pool=\"$pool\"}) ",
     "legendFormat": " used"
    },
    {
     "expr": "sum(jvm_memory_pool_bytes_used/jvm_memory_pool_bytes_max{job=\"$job\",pool=\"$pool\"}) ",
     "legendFormat": "used %%"
    },
    {
     "expr": "sum(jvm_memory_pool_bytes_max{job=\"$job\",pool=\"$pool\"})",
     "legendFormat": " max"
    },
    {
     "expr": "sum(jvm_memory_pool_bytes_committed{job=\"$job\",pool=\"$pool\"}) ",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_pool_bytes_used/jvm_memory_pool_bytes_max{job=\"$job\",pool=\"$pool\"}) ",
     "legendFormat": "committed %%"
    }
   ]
  },
  {
   "title": "$pool",
   "type": "graph",
   "gridPos": { "h": 11, "w": 4.8, "x": 4.8, "y": 34 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_pool_bytes_used{job=\"$job\",pool=\"$pool\"}) ",
     "legendFormat": " used"
    },
    {
     "expr": "sum(jvm_memory_pool_bytes_used/jvm_memory_pool_bytes_max{job=\"$job\",pool=\"$pool\"}) ",
     "legendFormat": "used %%"
    },
    {
     "expr": "sum(jvm_memory_pool_bytes_max{job=\"$job\",pool=\"$pool\"})",
     "legendFormat": " max"
    },
    {
     "expr": "sum(jvm_memory_pool_bytes_committed{job=\"$job\",pool=\"$pool\"}) ",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_pool_bytes_used/jvm_memory_pool_bytes_max{job=\"$job\",pool=\"$pool\"}) ",
     "legendFormat": "committed %%"
    }
   ]
  },
  {
   "title": "$pool",
   "type": "graph",
   "gridPos": { "h": 11, "w": 4.8, "x": 9.6, "y": 34 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_pool_bytes_used{job=\"$job\",pool=\"$pool\"}) ",
     "legendFormat": " used"
    },
    {
     "expr": "sum(jvm_memory_pool_bytes_used/jvm_memory_pool_bytes_max{job=\"$job\",pool=\"$pool\"}) ",
     "legendFormat": "used %%"
    },
    {
     "expr": "sum(jvm_memory_pool_bytes_max{job=\"$job\",pool=\"$pool\"})",
     "legendFormat": " max"
    },
    {
     "expr": "sum(jvm_memory_pool_bytes_committed{job=\"$job\",pool=\"$pool\"}) ",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_pool_bytes_used/jvm_memory_pool_bytes_max{job=\"$job\",pool=\"$pool\"}) ",
     "legendFormat": "committed %%"
    }
   ]
  },
  {
   "title": "$pool",
   "type": "graph",
   "gridPos": { "h": 11, "w": 4.8, "x": 14.399999999999999, "y": 34 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_pool_bytes_used{job=\"$job\",pool=\"$pool\"}) ",
     "legendFormat": " used"
    },
    {
     "expr": "sum(jvm_memory_pool_bytes_used/jvm_memory_pool_bytes_max{job=\"$job\",pool=\"$pool\"}) ",
     "legendFormat": "used %%"
    },
    {
     "expr": "sum(jvm_memory_pool_bytes_max{job=\"$job\",pool=\"$pool\"})",
     "legendFormat": " max"
    },
    {
     "expr": "sum(jvm_memory_pool_bytes_committed{job=\"$job\",pool=\"$pool\"}) ",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_pool_bytes_used/jvm_memory_pool_bytes_max{job=\"$job\",pool=\"$pool\"}) ",
     "legendFormat": "committed %%"
    }
   ]
  },
  {
   "title": "$pool",
   "type": "graph",
   "gridPos": { "h": 11, "w": 4.8, "x": 19.2, "y": 34 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_pool_bytes_used{job=\"$job\",pool=\"$pool\"}) ",
     "legendFormat": " used"
    },
    {
     "expr": "sum(jvm_memory_pool_bytes_used/jvm_memory_pool_bytes_max{job=\"$job\",pool=\"$pool\"}) ",
     "legendFormat": "used %%"
    },
    {
     "expr": "sum(jvm_memory_pool_bytes_max{job=\"$job\",pool=\"$pool\"})",
     "legendFormat": " max"
    },
    {
     "expr": "sum(jvm_memory_pool_bytes_committed{job=\"$job\",pool=\"$pool\"}) ",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_pool_bytes_used/jvm_memory_pool_bytes_max{job=\"$job\",pool=\"$pool\"}) ",
     "legendFormat": "committed %%"
    }
   ]
  }
 ]
}